config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "tops#index"
  namespace :flows do
    resources :searches, only: :index
  end 

  resources :flows do
    collection do
      get 'report' 
    end 
  end   
end

app/models/flow.rb
class Flow < ApplicationRecord


  validates :income1, :income2, :income3, :income4, :income5, :income6, :income7, presence: true,
    numericality: {
      only_integer: true,
      more_than_or_equal_to: 0, 
      allow_blank: true
    } 
  validates :expense1, :expense2, :expense3, :expense4, :expense5, :expense6, :expense7, presence: true,
  numericality: {
    only_integer: true,
    more_than_or_equal_to: 0, 
    allow_blank: true
  }   
  
  validates :year_month_day, uniqueness: true
  validates :year_month_day, presence: true

  before_save do
    self.income_total = ( income1 + income2 + income3 + income4 + income5 + income6 + income7 )
    self.expense_total = ( expense1 + expense2 + expense3 + expense4 + expense5 + expense6 + expense7 )
    
    
  end

end

app/controllers/flows/searches_controller.rb
class Flows::SearchesController < ApplicationController

  def index
    @q = Flow.ransack(params[:q])
    @flow_search = @q.result(distinct: true)
      unless @flow_search.exists?
        flash[:alert] = 'この日付にデータは登録されていません'
        redirect_to flows_path    
      else

      end  
  end

  private
  def search_params
    params.require(:q).permit(:year_mpnth_day_eq)
  end
  
end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController

  before_action :set_flow, only: [:edit, :show, :update]

  def index
    @q = Flow.ransack(params[:q])
    @flows = @q.result(distinct: true)
    @flows = Flow.order("year_month_day DESC").page(params[:page]).per(10)
    
  end  

  def new
      @flow = Flow.new
  end
  
  def create
    @flow = Flow.new(flow_params)
    
    if @flow.save 
      flash.now[:notice] = '登録に成功しました。'
      render 'show' #成功の場合
    else   #失敗の場合
      flash.now[:alert] = '登録に失敗しました。この日付には既にデータが登録されているか入力漏れがあります。'
      render 'new' 
    end 
  end     

  def show
  end 

  def destroy
    flow = Flow.find(params[:id])
     if flow.destroy
      flash.now[:notice] = 'データを削除しました'
      render 'destroy'
     else
      flash.now[:alert] = 'データ削除に失敗しました'
      render 'show'
     end 
  end   

  def edit
  end  

  def update
    if @flow.update(flow_params)
      flash.now[:notice] = '編集に成功しました'
      render 'show' 
    else
      flash.now[:alert] = '編集に失敗しました。全項目に入力してください'
      render 'edit'
    end  
  end

  def report
    # 1月集計
    @from = Date.new(2020, 01 ,01)
    @to = Date.new(2020, 01 ,31)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_jan = @flows.sum(:income_total)
    @flow_expense_total_jan = @flows.sum(:expense_total)
    @flow_balance_total_jan = ( @flow_income_total_jan - @flow_expense_total_jan )
    @flow_carryover_jan = 5000000 + @flow_balance_total_jan

    # 2月集計
    @from = Date.new(2020, 02 ,01)
    @to = Date.new(2020, 02 ,29)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_feb = @flows.sum(:income_total)
    @flow_expense_total_feb = @flows.sum(:expense_total)
    @flow_balance_total_feb = ( @flow_income_total_feb - @flow_expense_total_feb )
    @flow_carryover_feb = @flow_carryover_jan + @flow_balance_total_feb

    # 3月集計
    @from = Date.new(2020, 03 ,01)
    @to = Date.new(2020, 03 ,31)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_mar = @flows.sum(:income_total)
    @flow_expense_total_mar = @flows.sum(:expense_total)
    @flow_balance_total_mar = ( @flow_income_total_mar - @flow_expense_total_mar )
    @flow_carryover_mar = @flow_carryover_feb + @flow_balance_total_mar

    # 4月集計
    @from = Date.new(2020, 04 ,01)
    @to = Date.new(2020, 04 ,30)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_apr = @flows.sum(:income_total)
    @flow_expense_total_apr = @flows.sum(:expense_total)
    @flow_balance_total_apr = ( @flow_income_total_apr - @flow_expense_total_apr )
    @flow_carryover_apr = @flow_carryover_mar + @flow_balance_total_apr   
 
    # 5月集計
    @from = Date.new(2020, 05 ,01)
    @to = Date.new(2020, 05 ,31)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_may = @flows.sum(:income_total)
    @flow_expense_total_may = @flows.sum(:expense_total)
    @flow_balance_total_may = ( @flow_income_total_may - @flow_expense_total_may )
    @flow_carryover_may = @flow_carryover_apr + @flow_balance_total_may   

    # 6月集計
    @from = Date.new(2020, 06 ,01)
    @to = Date.new(2020, 06 ,30)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_jun = @flows.sum(:income_total)
    @flow_expense_total_jun = @flows.sum(:expense_total)
    @flow_balance_total_jun = ( @flow_income_total_jun - @flow_expense_total_jun )
    @flow_carryover_jun = @flow_carryover_may + @flow_balance_total_jun   

    # 7月集計
    @from = Date.new(2020, 07 ,01)
    @to = Date.new(2020, 07 ,31)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_jul = @flows.sum(:income_total)
    @flow_expense_total_jul = @flows.sum(:expense_total)
    @flow_balance_total_jul = ( @flow_income_total_jul - @flow_expense_total_jul )
    @flow_carryover_jul = @flow_carryover_jun + @flow_balance_total_jul   

    # 8月集計
    @from = Date.new(2020, 8 ,01)
    @to = Date.new(2020, 8 ,31)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_aug = @flows.sum(:income_total)
    @flow_expense_total_aug = @flows.sum(:expense_total)
    @flow_balance_total_aug = ( @flow_income_total_aug - @flow_expense_total_aug )
    @flow_carryover_aug = @flow_carryover_jul + @flow_balance_total_aug

    # 9月集計
    @from = Date.new(2020, 9 ,01)
    @to = Date.new(2020, 9 ,30)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_sep = @flows.sum(:income_total)
    @flow_expense_total_sep = @flows.sum(:expense_total)
    @flow_balance_total_sep = ( @flow_income_total_sep - @flow_expense_total_sep )
    @flow_carryover_sep = @flow_carryover_aug + @flow_balance_total_sep

    # 10月集計
    @from = Date.new(2020, 10 ,01)
    @to = Date.new(2020, 10 ,31)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_oct = @flows.sum(:income_total)
    @flow_expense_total_oct = @flows.sum(:expense_total)
    @flow_balance_total_oct = ( @flow_income_total_oct - @flow_expense_total_oct )
    @flow_carryover_oct = @flow_carryover_sep + @flow_balance_total_oct

    # 11月集計
    @from = Date.new(2020, 11 ,01)
    @to = Date.new(2020, 11 ,30)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_nov = @flows.sum(:income_total)
    @flow_expense_total_nov = @flows.sum(:expense_total)
    @flow_balance_total_nov = ( @flow_income_total_nov - @flow_expense_total_nov )
    @flow_carryover_nov = @flow_carryover_oct + @flow_balance_total_nov

    # 12月集計
    @from = Date.new(2020, 12 ,01)
    @to = Date.new(2020, 12 ,31)
    @flows = Flow.where(year_month_day: @from..@to)
    @flow_income_total_dec = @flows.sum(:income_total)
    @flow_expense_total_dec = @flows.sum(:expense_total)
    @flow_balance_total_dec = ( @flow_income_total_dec - @flow_expense_total_dec )
    @flow_carryover_dec = @flow_carryover_nov + @flow_balance_total_dec 
  
    gon.data_income = [ @flow_income_total_jan, 
                        @flow_income_total_feb,
                        @flow_income_total_mar,
                        @flow_income_total_apr,
                        @flow_income_total_may,
                        @flow_income_total_jun,
                        @flow_income_total_jul,
                        @flow_income_total_aug,
                        @flow_income_total_sep,
                        @flow_income_total_oct,
                        @flow_income_total_nov,
                        @flow_income_total_dec ]
                        
    12.times do
      gon.data_income << rand(100.0)
    end  
    
      gon.data_expense = [ @flow_expense_total_jan, 
                           @flow_expense_total_feb,
                           @flow_expense_total_mar,
                           @flow_expense_total_apr,
                           @flow_expense_total_may,
                           @flow_expense_total_jun,
                           @flow_expense_total_jul,
                           @flow_expense_total_aug,
                           @flow_expense_total_sep,
                           @flow_expense_total_oct,
                           @flow_expense_total_nov,
                           @flow_expense_total_dec ]
    12.times do
      gon.data_expense << rand(100.0)
    end  

    gon.data_carryover = [ @flow_carryover_jan, 
                           @flow_carryover_feb,
                           @flow_carryover_mar,
                           @flow_carryover_apr,
                           @flow_carryover_may,
                           @flow_carryover_jun,
                           @flow_carryover_jul,
                           @flow_carryover_aug,
                           @flow_carryover_sep,
                           @flow_carryover_oct,
                           @flow_carryover_nov,
                           @flow_carryover_dec ]
    12.times do
      gon.data_income << rand(100.0)
    end  
  end  


  def set_flow #showとedit,#updateでの処理
    @flow = Flow.find(params[:id]) 
  end

  private
  def flow_params
    params.require(:flow).permit(:year_month_day, :income1, :income2, :income3, :income4, :income5, :income6, :income7, :income_total,
                                 :expense1, :expense2, :expense3, :expense4, :expense5, :expense6, :expense7, :expense_total, :text) 
  end  
end

app/helpers/flows/searches_helper.rb
module Flows::SearchesHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/views/flows/_form.html.erb
   <div class="main_flow_income">
      <table class="attr">
        <colgroup>
            <col style="width:50%;">
            <col style="width:50%;">
        </colgroup>
        <thead>
          <tr>
            <th>項目</th>
            <th>金額</th>     
          </tr>
        </thead>   
        <tr>
          <th><%= label :income1, "売上入金（振込/現金）" %></th>
          <td><%= form.number_field :income1, size: 8, class:"input" %>円</td>
        </tr>
        <tr>
          <th><%= label :income2, "売上入金（手形決済）" %></th>
          <td><%= form.number_field :income2, size: 8, class:"input" %>円</td>
        </tr>
        <tr>
          <th><%= label :income3, "受取利息" %></th>
          <td><%= form.number_field :income3, size: 8, class:"input" %>円</td>
        </tr>
        <tr>
          <th><%= label :income4, "借入金" %></th>
          <td><%= form.number_field :income4, size: 8, class:"input" %>円</td>
        </tr>
        <tr>
          <th><%= label :income5, "その他収入" %></th>
          <td><%= form.number_field :income5, size: 8, class:"input" %>円</td>
        </tr>
        <tr>
          <th><%= label :income6, "収入6" %></th>
          <td><%= form.number_field :income6, size: 8, class:"input" %>円</td>
        </tr>
        <tr>
          <th><%= label :income7, "収入7" %></th>
          <td><%= form.number_field :income7, size: 8, class:"input" %>円</td>
        </tr>
      </table>
    </div>

    <div class="main_flow_expense">
      <table class="attr">
          <colgroup>
              <col style="width:50%;">
              <col style="width:50%;">
          </colgroup>
          <thead>
            <tr>
              <th>項目</th>
              <th>金額</th>   
            </tr>
          </thead>
          <tr>
            <th><%= label :expense1, "仕入支払" %></th>
            <td><%= form.number_field :expense1, size: 8, class:"input_main" %>円</td>
          </tr>
          <tr>
            <th><%= label :expense2, "人件費" %></th>
            <td><%= form.number_field :expense2, size: 8, class:"input" %>円</td>
          </tr>
          <tr>
            <th><%= label :expense3, "家賃支払" %></th>
            <td><%= form.number_field :expense3, size: 8, class:"input" %>円</td>
          </tr>
          <tr>
            <th><%= label :expense4, "水道光熱費/通信費" %></th>
            <td><%= form.number_field :expense4, size: 8, class:"input" %>円</td>
          </tr>
          <tr>
            <th><%= label :expense5, "税金支払" %></th>
            <td><%= form.number_field :expense5, size: 8, class:"input" %>円</td>
          </tr>
          <tr>
            <th><%= label :expense6, "借入返済" %></th>
            <td><%= form.number_field :expense6, size: 8, class:"input" %>円</td>
          </tr>
          <tr>
            <th><%= label :expense7, "その他支払" %></th>
            <td><%= form.number_field :expense7, size: 8, class:"input" %>円</td>
          </tr>
        </table>        
      </div>
      <div class="main_flow_text">
        <%= form.text_area :text, placeholder: "備忘録" , rows: "4" %>
      </div>

app/views/flows/destroy.html.erb
<div class="main_flow">
  <%= link_to 'トップに戻る', root_path, method: :get,class: 'btn btn-default' %> 
</div>

app/views/flows/edit.html.erb
<div class="main_flow">
  <%= form_for @flow do |form| %>
    <div class="registration_show">
       <%= @flow.year_month_day&.strftime("%Y年%-m月%-d日") %>
    </div>
      <%= render partial: "form", locals: { form: form } %>
    <div class="submit">
      <%= form.submit  value="編集完了する",class: 'btn btn-default' %>
    </div>  
   <% end %>   
</div>      

app/views/flows/index.html.erb
<div class="main_flow">
  <div class="registration_search">
    <%= search_form_for @q, url: flows_searches_path, method: :get, class: "registration_search" do |form| %>
        <%= form.label :year_month_day_eq, "検索日", class:"search_registration_label" %>
        <%= form.date_field :year_month_day_eq %>
        <%= form.submit "検索", class:'btn btn-default' %>      
    <% end %>
  </div>

  <div class="main_flow_search">
    <table class="attr3">
      <colgroup>
          <col style="width:10%;">
          <col style="width:15%;">
          <col style="width:15%;">
          <col style="width:15%;">
          <col style="width:15%;">
      </colgroup>
      <thead>
        <tr>
          <th>内訳確認</th>
          <th>日付</th>
          <th>収入合計</th> 
          <th>支出合計</th>     
          <th>収支額</th>         
        </tr>
      </thead>
      <% @flows.each do |flow| %>       
          <tr>
            <td><%= link_to '内訳を見る', "/flows/#{flow.id}", method: :get,class: 'btn btn-default' %> </td>
            <td><%= flow.year_month_day&.strftime("%Y年%-m月%-d日") %></td>
            <td><%= flow.income_total.to_s(:delimited, delimiter: ',') %>円</td>
            <td><%= flow.expense_total.to_s(:delimited, delimiter: ',') %>円</td>
            <td><%= (flow.income_total - flow.expense_total).to_s(:delimited, delimiter: ',') %>円</td>
          </tr>
      <% end %>     
    </table>
      <%= paginate(@flows) %> 
  </div>  
</div>
    

app/views/flows/new.html.erb
<div class="main_flow">
  <%= form_for @flow do |form| %>
    <div class="registration">
      <%= form.label :registration_day, "登録日", class:"registration_label" %>
      <%= form.date_field :year_month_day %>
      <%# <%= form.date_select :year_month_day,
        start_year: 2020, 
        end_year: (Time.current.year),
        use_month_numbers: true %> 
    </div>
      <%= render partial: "form", locals: { form: form } %>
    <div class="submit">
        <%= form.submit  value="登録する",class: 'btn btn-default' %>
        <%= link_to 'やり直す', new_flow_path, method: :get,class: 'btn btn-default' %> 
    </div>
   <% end %>   
</div>      

app/views/flows/report.html.erb
<div class="main_flow">
  <div class="main_flow_month_data_grafic">

    <canvas id="myChart" width="200" height="80"></canvas>
    <script>draw_graph();</script>  

  </div>
    <div class="main_flow_month_data">
      <table class="attr4">
        <colgroup>
          <col style="width:4%, text-aline: center;">
          <col style="width:8%;">
          <col style="width:8%;">
          <col style="width:8%;">
          <col style="width:8%;">
          <col style="width:8%;">
          <col style="width:8%;">
          <col style="width:8%;">
          <col style="width:8%;">
          <col style="width:8%;">
          <col style="width:8%;">
          <col style="width:8%;">
          <col style="width:8%;">
        </colgroup>
        <thead>
          <tr>
            <th>項目</th>
            <th>1月</th>
            <th>2月</th>
            <th>3月</th>
            <th>4月</th>
            <th>5月</th>
            <th>6月</th>
            <th>7月</th>
            <th>8月</th>
            <th>9月</th>
            <th>10月</th>
            <th>11月</th>
            <th>12月</th>
          </tr>
        </thead>      
        <tr>
          <td>収入</td>
          <td><%= @flow_income_total_jan.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_feb.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_mar.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_apr.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_may.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_jun.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_jul.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_aug.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_sep.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_oct.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_nov.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_income_total_dec.to_s(:delimited, delimiter: ',') %></td>
        </tr>
        <tr>
          <td>支出</td>
          <td><%= @flow_expense_total_jan.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_feb.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_mar.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_apr.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_may.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_jun.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_jul.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_aug.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_sep.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_oct.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_nov.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_expense_total_dec.to_s(:delimited, delimiter: ',') %></td>
        </tr>
        <tr>
          <td>収支</td>
          <td><%= @flow_balance_total_jan.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_feb.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_mar.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_apr.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_may.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_jun.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_jul.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_aug.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_sep.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_oct.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_nov.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_balance_total_dec.to_s(:delimited, delimiter: ',') %></td>
        </tr>
        <tr>
          <td>繰越</td>
          <td><%= @flow_carryover_jan.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_feb.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_mar.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_apr.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_may.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_jun.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_jul.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_aug.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_sep.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_oct.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_nov.to_s(:delimited, delimiter: ',') %></td>
          <td><%= @flow_carryover_dec.to_s(:delimited, delimiter: ',') %></td>
        </tr>   
      </table>
    </div>
</div>

app/views/flows/show.html.erb
<div class="main_flow">
    <div class="registration_show">
      <%= @flow.year_month_day&.strftime("%Y年%-m月%-d日") %>
    </div>
    <div class="main_flow_income">
      <table class="attr">
        <colgroup>
            <col style="width:50%;">
            <col style="width:50%;">
        </colgroup>
        <thead>
          <tr>
            <th>項目</th>
            <th>金額</th>     
          </tr>
        </thead>      
        <tr>
          <th><%= label :income1, "売上入金（振込/現金）" %></th>
          <td><%= @flow.income1.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
        <tr>
          <th><%= label :income2, "売上入金（手形決済）" %></th>
          <td><%= @flow.income2.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
        <tr>
          <th><%= label :income3, "受取利息" %></th>
          <td><%= @flow.income3.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
        <tr>
          <th><%= label :income4, "借入金" %></th>
          <td><%= @flow.income4.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
        <tr>
          <th><%= label :income5, "その他収入" %></th>
          <td><%= @flow.income5.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
        <tr>
          <th><%= label :income6, "収入6" %></th>
          <td><%= @flow.income6.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
        <tr>
          <th><%= label :income7, "収入7" %></th>
          <td><%= @flow.income7.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
        <tr>
          <th><%= label :income_total, "収入合計" %></th>
          <td><%= @flow.income_total.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
      </table>
    </div>

    <div class="main_flow_expense">
      <table class="attr">
          <colgroup>
              <col style="width:50%;">
              <col style="width:50%;">
          </colgroup>
          <thead>
            <tr>
              <th>項目</th>
              <th>金額</th>   
            </tr>
          </thead>
          <tr>
            <th><%= label :expense1, "仕入支払" %></th>
            <td><%= @flow.expense1.to_s(:delimited, delimiter: ',') %>円</td>
          </tr>
          <tr>
            <th><%= label :expense2, "人件費" %></th>
            <td><%= @flow.expense2.to_s(:delimited, delimiter: ',') %>円</td>
          </tr>
          <tr>
            <th><%= label :expense3, "家賃支払" %></th>
            <td><%= @flow.expense3.to_s(:delimited, delimiter: ',') %>円</td>
          </tr>
          <tr>
            <th><%= label :expense4, "水道光熱費/通信費" %></th>
            <td><%= @flow.expense4.to_s(:delimited, delimiter: ',') %>円</td>
          </tr>
          <tr>
            <th><%= label :expense5, "税金支払" %></th>
            <td><%= @flow.expense5.to_s(:delimited, delimiter: ',') %>円</td>
          </tr>
          <tr>
            <th><%= label :expense6, "借入返済" %></th>
            <td><%= @flow.expense6.to_s(:delimited, delimiter: ',') %>円</td>
          </tr>
          <tr>
            <th><%= label :expense7, "その他支払" %></th>
            <td><%= @flow.expense7.to_s(:delimited, delimiter: ',') %>円</td>
          </tr>
          <tr>
            <th><%= label :expense_total, "支出合計" %></th>
            <td><%= @flow.expense_total.to_s(:delimited, delimiter: ',') %>円</td>
          </tr>
      </table>        
    </div>

      <div class="main_flow_termflow">
        <table class="attr2">
          <colgroup>
              <col style="width:55%;">
              <col style="width:45%;">
          </colgroup>
          <thead>
            <tr>
              <th>項目</th>
              <th>金額</th>     
            </tr>
          </thead>  
          <tr>
            <th><%= label :termflow2, "収支額" %></th>
            <td><%= (@flow.income_total - @flow.expense_total).to_s(:delimited, delimiter: ',') %>円</td>         
          </tr>
        </table>
        <%= link_to '編集する', "/flows/#{@flow.id}/edit", method: :get,class: 'btn btn-default' %> 
        <%= link_to '削除する', "/flows/#{@flow.id}", method: :delete,class: 'btn btn-default' %> 
        <%= link_to 'トップに戻る', root_path, method: :get,class: 'btn btn-default' %> 
      </div> 
      <div class="main_flow_text">    
      　<div class="main_flow_text-box" >
          <%= @flow.text %>
        </div>
      </div>         
</div>