config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "tops#index"
  namespace :flows do
    resources :searches, only: :index
  end 

  resources :flows do
    collection do
      get 'report' 
    end 
  end   
end

app/views/shared/_footer.html.erb
<p>
  Copyright Minicashflow 2020.
</p>

app/views/shared/_header.html.erb
<nav class="menubar">
  <% if user_signed_in? %>
    <ul> 
      <%= link_to "TOP", :root %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= link_to "アカウント変更", edit_user_registration_path, method: :get %>
         <%= current_user.family_name %>さんがログインしています 
    </ul> 
  <% else %>
      <%= link_to "ログイン", new_user_session_path, class: 'post'  %>
      <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
  <% end %>

app/views/shared/_side_bar.html.erb
<div class="side_bar">

  <div class="side_bar_upper">
    <h2>データ登録</h2>
    <% if user_signed_in? && current_user.id %>
      <%= link_to '登録する', new_flow_path, method: :get,class: 'btn btn-default' %>  
    <% end %> 
  </div>

  <div class="side_bar_middle"> 
    <h2>データ検索</h2>
    <div class="registration_search">  
      <% if user_signed_in? && current_user.id %>
        <%= link_to '検索する',  flows_path, method: :get,class: 'btn btn-default' %>
      <% end %>    
    </div>  
  </div> 
   <div class="side_bar_under"> 
    <h2>データ集計(月別)</h2>
    <div class="registration_search">  
      <% if user_signed_in? && current_user.id %>
        <%= link_to '集計する',  report_flows_path, method: :get,class: 'btn btn-default' %>
      <% end %>    
    </div>  
  </div> 
</div>